"use client";
import { FormEvent, useMemo, useState } from "react";
type CodeRow={code:string;activated_at:number|null;expires_at:number|null;usage_count:number;created_at:number;device_bound:number};
type LogRow={action:string;detail:string;created_at:number};
export default function AdminPage(){
 const[key,setKey]=useState(""),[logged,setLogged]=useState(false),[codes,setCodes]=useState<CodeRow[]>([]),[logs,setLogs]=useState<LogRow[]>([]),[serverTime,setServerTime]=useState(Date.now()),[error,setError]=useState(""),[loading,setLoading]=useState(false),[count,setCount]=useState(10),[filter,setFilter]=useState("全部"),[query,setQuery]=useState(""),[copied,setCopied]=useState("");
 function status(row:CodeRow){if(!row.activated_at)return"未使用";if(row.expires_at&&serverTime>row.expires_at)return"已过期";return"使用中"}
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/invites");const d=await r.json();if(!r.ok){if(r.status===401)setLogged(false);throw new Error(d.message||"加载失败")}setCodes(d.codes);setLogs(d.logs||[]);setServerTime(d.serverTime);setLogged(true)}catch(e){setError(e instanceof Error?e.message:"请求失败")}finally{setLoading(false)}}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:key})});const d=await r.json();if(!r.ok)throw new Error(d.message||"登录失败");setKey("");await load()}catch(e){setError(e instanceof Error?e.message:"登录失败");setLoading(false)}}
 async function logout(){await fetch("/api/admin/session",{method:"DELETE"});setLogged(false);setCodes([]);setLogs([])}
 async function generate(){setLoading(true);setError("");try{const r=await fetch("/api/admin/invites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({count})});const d=await r.json();if(!r.ok)throw new Error(d.message||"生成失败");await load()}catch(e){setError(e instanceof Error?e.message:"生成失败");setLoading(false)}}
 async function copy(value:string){await navigator.clipboard.writeText(value);setCopied(value);setTimeout(()=>setCopied(""),1500)}
 const stats=useMemo(()=>({unused:codes.filter(c=>status(c)==="未使用").length,active:codes.filter(c=>status(c)==="使用中").length,expired:codes.filter(c=>status(c)==="已过期").length}),[codes,serverTime]),visible=codes.filter(c=>(filter==="全部"||status(c)===filter)&&c.code.toLowerCase().includes(query.toLowerCase()));
 if(!logged)return <main className="admin-login"><form onSubmit={login}><div className="admin-logo">M</div><span>INNER AGE CONTROL</span><h1>邀请码管理后台</h1><p>登录成功后使用 8 小时安全会话；连续失败 5 次将临时封禁。</p><label>管理员密码<input type="password" value={key} onChange={e=>setKey(e.target.value)} autoFocus placeholder="输入管理密码"/></label>{error&&<em>{error}</em>}<button disabled={loading}>{loading?"正在验证…":"进入后台"}</button><a href="/">← 返回测试首页</a></form></main>;
 return <main className="admin-shell"><header><div><b><i>M</i> INNER AGE</b><span>邀请码管理中心</span></div><div><a href="/" target="_blank">打开测试页 ↗</a><button onClick={logout}>安全退出</button></div></header><section className="admin-content"><div className="admin-title"><div><span>INVITATION CENTER</span><h1>邀请码管理</h1><p>首次激活绑定浏览器，当前设备可在 24 小时内重复测试。</p></div><button onClick={load} disabled={loading}>↻ 刷新状态</button></div><div className="admin-stats"><div><i className="unused"/> <span>未使用</span><b>{stats.unused}</b><small>尚未开始计时</small></div><div><i className="active"/> <span>使用中</span><b>{stats.active}</b><small>已绑定设备</small></div><div><i className="expired"/> <span>已过期</span><b>{stats.expired}</b><small>已停止访问</small></div><div><i className="total"/> <span>总计</span><b>{codes.length}</b><small>全部正式邀请码</small></div></div><section className="generator"><div><span>SECURE CODES</span><h2>创建长随机邀请码</h2><p>每次最多 100 个，约 60 位随机熵；不再支持公开体验码。</p></div><label>生成数量<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,5,10,20,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button onClick={generate} disabled={loading}>＋ {loading?"处理中":"立即生成"}</button></section>{error&&<p className="admin-error">! {error}</p>}<section className="code-panel"><div className="code-tools"><div className="filters">{["全部","未使用","使用中","已过期"].map(v=><button className={filter===v?"selected":""} onClick={()=>setFilter(v)} key={v}>{v}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索邀请码"/></div><div className="code-table"><div className="table-head"><span>邀请码</span><span>状态</span><span>激活时间</span><span>到期时间</span><span>使用次数</span><span>操作</span></div>{visible.length===0?<p className="empty">暂无符合条件的邀请码</p>:visible.map(row=><div className="table-row" key={row.code}><b>{row.code}</b><span><i className={status(row)}/>{status(row)}</span><span>{row.activated_at?new Date(row.activated_at).toLocaleString("zh-CN"):"—"}</span><span>{row.expires_at?new Date(row.expires_at).toLocaleString("zh-CN"):"—"}</span><span>{row.usage_count} 次</span><button onClick={()=>copy(row.code)}>{copied===row.code?"已复制 ✓":"复制"}</button></div>)}</div><p className="table-note">当前显示 {visible.length} 个邀请码 · 时间以服务器为准</p></section><section className="audit-panel"><h2>最近安全审计</h2><p>记录后台登录、退出和邀请码生成操作（IP 仅保存不可逆摘要）。</p>{logs.map((log,i)=><div key={log.created_at+"-"+i}><b>{log.action}</b><span>{log.detail||"—"}</span><time>{new Date(log.created_at).toLocaleString("zh-CN")}</time></div>)}</section></section></main>
}
