create table if not exists public.invites (
  code varchar(64) primary key,
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  expires_at timestamptz,
  device_hash varchar(64),
  usage_count integer not null default 0,
  disabled boolean not null default false
);
create table if not exists public.rate_limits (
  id varchar(64) primary key,
  scope varchar(32) not null,
  attempts integer not null default 0,
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action varchar(64) not null,
  detail text,
  actor_hash varchar(64),
  created_at timestamptz not null default now()
);
create index if not exists invites_status_idx on public.invites (activated_at, expires_at, disabled);
create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc);
alter table public.invites enable row level security;
alter table public.rate_limits enable row level security;
alter table public.audit_logs enable row level security;
revoke all on public.invites, public.rate_limits, public.audit_logs from anon, authenticated;
grant select, insert, update, delete on public.invites, public.rate_limits, public.audit_logs to service_role;
grant usage, select on sequence public.audit_logs_id_seq to service_role;
