"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Stage="entry"|"quiz"|"loading"|"result";
type Dim="curiosity"|"stability"|"social"|"responsibility"|"adaptability"|"acceptance";
type Question={text:string;dim:Dim;options:string[]};
type Result={actual:number;mental:number;score:number;dims:Record<Dim,number>;title:string;identity:string;keywords:string[]};

const dimNames:Record<Dim,string>={curiosity:"好奇心",stability:"情绪稳定",social:"社交开放",responsibility:"责任担当",adaptability:"适应力",acceptance:"自我接纳"};
const questions:Question[]=[
 {dim:"curiosity",text:"忽然拥有一个完全自由的周末，你更想？",options:["待在熟悉的地方，好好休息","完成拖延已久的事情","约朋友尝试一家新店","去一个陌生地方即兴探索"]},
 {dim:"responsibility",text:"得到一笔意外之财（数额不大），你会？",options:["立刻买心仪已久的东西","请朋友吃饭，一起开心","一部分享受，一部分储蓄","优先储蓄或投入长期计划"]},
 {dim:"stability",text:"计划被临时打乱时，你通常会？",options:["很烦躁，需要较久才能恢复","先抱怨一下，再重新安排","接受变化，寻找替代方案","觉得意外也可能带来新机会"]},
 {dim:"social",text:"来到一个几乎没有熟人的聚会，你会？",options:["找个安静角落等待结束","只和认识的人待在一起","愿意回应别人，但不主动","主动认识几位有趣的人"]},
 {dim:"acceptance",text:"别人指出你的缺点时，你的第一反应是？",options:["感觉被否定，想立刻反驳","表面接受，心里反复想","分辨哪些部分值得参考","感谢反馈，但不因此否定自己"]},
 {dim:"adaptability",text:"工作或学习进入陌生领域，你更接近？",options:["担心做不好，倾向于回避","希望有人给出完整步骤","边学边做，允许小范围试错","感到兴奋，迅速建立方法"]},
 {dim:"responsibility",text:"面对一项重要但不紧急的任务，你会？",options:["常常拖到截止前","想到时做一点","拆分计划并逐步完成","提前完成并预留检查时间"]},
 {dim:"curiosity",text:"与你观点完全不同的人认真交流时，你会？",options:["尽快结束话题","努力证明自己是对的","听完后保留各自看法","追问他的经历与思考路径"]},
 {dim:"stability",text:"经历一次明显失败后，你通常需要多久恢复？",options:["很久，常反复责怪自己","几天，需要他人安慰","复盘后能继续行动","很快，把它当作有效反馈"]},
 {dim:"social",text:"朋友情绪低落向你倾诉，你会？",options:["不知道说什么，想躲开","立刻告诉对方该怎么做","认真倾听，再询问需要什么","陪伴倾听，也尊重彼此边界"]},
 {dim:"acceptance",text:"看到同龄人取得很大成就时，你更可能？",options:["焦虑，觉得自己落后了","羡慕并怀疑自己的选择","欣赏对方，也审视自己的节奏","真诚祝福，知道人生没有统一时钟"]},
 {dim:"adaptability",text:"使用一款全新的数字工具时，你会？",options:["能不用就不用","等别人教会我","看教程后按需使用","主动试遍功能并优化流程"]},
 {dim:"curiosity",text:"你上一次纯粹因为好奇学习新东西，是？",options:["想不起来了","半年以前","最近一个月","就在最近一周"]},
 {dim:"responsibility",text:"做重大决定时，你通常依据什么？",options:["当下感觉","身边人的意见","利弊分析与直觉结合","长期目标、风险与真实需求"]},
 {dim:"stability",text:"深夜突然想起一件尴尬往事，你会？",options:["陷进去，越想越难受","强迫自己不要想","提醒自己那已经过去","笑一笑，接纳当时不完美的自己"]},
 {dim:"social",text:"一段关系让你持续疲惫时，你会？",options:["忍着，害怕失去关系","突然疏远，不解释原因","尝试沟通自己的感受","清晰表达边界，也尊重对方选择"]},
 {dim:"adaptability",text:"如果理想生活必须从头开始，你会？",options:["宁愿维持现状","等准备充分再行动","先迈出可逆的一小步","接受不确定，行动中调整方向"]},
 {dim:"acceptance",text:"你怎样看待自己尚未做到的事？",options:["证明我能力不足","让我对自己失望","它提醒我需要调整方法","它只是成长过程中的一段路"]},
 {dim:"responsibility",text:"身体已经疲惫，但事情还没做完，你会？",options:["硬撑到底，不管身体","全部放下，以后再说","判断优先级，完成关键部分","照顾身体并重新承诺明确时间"]},
 {dim:"acceptance",text:"测试结束了，你现在的感受是？",options:["担心结果不够好","希望答案证明我很成熟","好奇自己的选择呈现了什么","无论结果如何，都愿意理解自己"]},
];

function ageFromBirth(birth:string){const b=new Date(`${birth}T00:00:00`),n=new Date();let age=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))age--;return age}
export default function Home(){const[stage,setStage]=useState<Stage>("entry");const[code,setCode]=useState("");const now=new Date();const[year,setYear]=useState(1996);const[month,setMonth]=useState(11);const[day,setDay]=useState(8);const[error,setError]=useState("");const[checking,setChecking]=useState(false);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<number[]>([]);const[load,setLoad]=useState(0);const[result,setResult]=useState<Result|null>(null);const daysInMonth=new Date(year,month,0).getDate();const safeDay=Math.min(day,daysInMonth);const birth=`${year}-${String(month).padStart(2,"0")}-${String(safeDay).padStart(2,"0")}`;
 async function start(e:FormEvent){e.preventDefault();if(ageFromBirth(birth)<10||ageFromBirth(birth)>100){setError("请选择有效的出生日期");return}setChecking(true);setError("");try{let response=await fetch("/api/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});if(response.status===503){await new Promise(r=>setTimeout(r,600));response=await fetch("/api/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})})}const data=await response.json() as {valid:boolean;message?:string};if(!response.ok||!data.valid){setError(data.message||"邀请码验证失败");return}setStage("quiz");window.scrollTo(0,0)}catch{setError("暂时无法验证邀请码，请稍后再试")}finally{setChecking(false)}}
 async function answer(value:number){const next=[...answers,value];setAnswers(next);if(index<questions.length-1){setIndex(index+1);window.scrollTo({top:0,behavior:"smooth"});return}setChecking(true);setError("");try{const response=await fetch("/api/result",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({birth,answers:next})});const data=await response.json() as Result&{message?:string};if(!response.ok)throw new Error(data.message||"报告生成失败");setResult(data);setStage("loading");setLoad(8)}catch(e){setAnswers(answers);setError(e instanceof Error?e.message:"报告生成失败，请稍后重试")}finally{setChecking(false)}}
 useEffect(()=>{if(stage!=="loading")return;const t=setInterval(()=>setLoad(v=>{if(v>=100){clearInterval(t);setTimeout(()=>{setStage("result");window.scrollTo(0,0)},350);return 100}return Math.min(100,v+7)}),130);return()=>clearInterval(t)},[stage]);
 function reset(){setStage("entry");setIndex(0);setAnswers([]);setResult(null);setLoad(0);setCode("");window.scrollTo({top:0,behavior:"smooth"})}
 async function share(){const text=`我的心理年龄是 ${result?.mental} 岁——${result?.title}。来测测你内心住着多少岁的自己？`;if(navigator.share)await navigator.share({title:"Inner Age 心理年纪测试",text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);alert("结果文案已复制")}}
 return <main className={`mind-app stage-${stage}`}>
  {stage==="entry"&&<section className="entry-wrap"><header className="mini-nav"><b><i>M</i> INNER AGE</b><span>多维观察 · 温和洞察</span></header><div className="hero-orbit"><span/><span/><div>?</div></div><p className="kicker">心理年纪 · 人格画像</p><h1>你内心住着<br/><em>多少岁的自己？</em></h1><p className="lead">20 个生活情境，6 个心理维度。答案没有对错，只需要选择最像真实自己的那一个。</p><form className="entry-card" onSubmit={start}><span className="step-chip">开始前 · 约 5 分钟</span><h2>先确认你的测试信息</h2><label>邀请码<div className="input-wrap"><span>⌘</span><input value={code} onChange={e=>setCode(e.target.value)} placeholder="请输入邀请码" autoComplete="off"/></div></label><p className="invite-hint">首次使用将绑定当前浏览器，24 小时内可在本设备重复测试</p><label>真实出生日期</label><div className="birth-selects"><label><span>年份</span><select value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:91},(_,i)=>now.getFullYear()-10-i).map(v=><option key={v}>{v}</option>)}</select></label><label><span>月份</span><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}月</option>)}</select></label><label><span>日期</span><select value={Math.min(day,daysInMonth)} onChange={e=>setDay(Number(e.target.value))}>{Array.from({length:daysInMonth},(_,i)=>i+1).map(v=><option key={v} value={v}>{v}日</option>)}</select></label></div>{error&&<p className="error">! {error}</p>}<button className="primary" disabled={checking}>{checking?"正在验证…":"进入测试"} <span>→</span></button><small>生日与答案仅用于即时生成本次结果，服务器不保存测试内容</small></form><div className="trust-row"><span>◈ 无需登录，即时结果</span><span>◌ 结果因人而异</span><span>⌁ 不保存测评内容</span></div><p className="compliance-note">本测试仅用于娱乐与自我探索，不构成心理咨询、医疗诊断、就业或其他专业判断，也不承诺临床准确性。</p></section>}
  {stage==="quiz"&&<Quiz index={index} answers={answers} onAnswer={answer} onBack={()=>{if(index>0){setIndex(index-1);setAnswers(answers.slice(0,-1))}else setStage("entry")}} error={error} busy={checking}/>}
  {stage==="loading"&&<Loading progress={load}/>} {stage==="result"&&result&&<Report result={result} onReset={reset} onShare={share} onHome={reset}/>} 
 </main>}

function Quiz({index,answers,onAnswer,onBack,error,busy}:{index:number;answers:number[];onAnswer:(n:number)=>void;onBack:()=>void;error:string;busy:boolean}){const q=questions[index];return <section className="quiz-wrap"><header className="quiz-head"><button onClick={onBack}>←</button><div><b>INNER AGE</b><span>{dimNames[q.dim]}维度</span></div><em>{String(index+1).padStart(2,"0")} / {questions.length}</em></header><div className="quiz-progress"><span style={{width:`${(index+1)/questions.length*100}%`}}/></div><div className="question-meta"><span>QUESTION {String(index+1).padStart(2,"0")}</span><b>{Math.round((index+1)/questions.length*100)}%</b></div><article className="question-card" key={index}><div className="question-symbol">{["✦","◌","△","◇"][index%4]}</div><h1>{q.text}</h1><p>别想太久，第一反应往往更接近真实的你。</p><div className="options">{q.options.map((o,i)=><button disabled={busy} key={o} onClick={()=>onAnswer(i)}><span>{String.fromCharCode(65+i)}</span>{o}<i>→</i></button>)}</div>{error&&<p className="error">! {error}</p>}</article><p className="quiz-note">你的作答仅保存在当前测试中 · 已完成 {answers.length} 题</p></section>}

function Loading({progress}:{progress:number}){const steps:[number,string,string][]=[[20,"读取作答轨迹","整理选择倾向"],[48,"映射心理维度","计算六维特征"],[76,"识别人格原型","匹配年龄画像"],[96,"生成完整报告","整理洞察与建议"]];return <section className="loading-wrap"><div className="load-card"><p className="kicker">RESULT SYNTHESIS</p><div className="pulse"><i>{progress}</i><span>%</span></div><h1>{progress<48?"正在读取你的选择":progress<76?"正在辨认你的内在节奏":progress<96?"正在拼合你的心理画像":"报告即将完成"}</h1><p>每一次选择都在描绘你面对世界的方式。</p><div className="load-bar"><span style={{width:`${progress}%`}}/></div><div className="load-steps">{steps.map(([at,title,sub])=><div key={title} className={progress>=at?"done":progress+25>=at?"doing":""}><i>{progress>=at?"✓":"·"}</i><span><b>{title}</b><small>{sub}</small></span><em>{progress>=at?"已完成":progress+25>=at?"处理中":"等待中"}</em></div>)}</div></div></section>}

function Radar({dims}:{dims:Record<Dim,number>}){const keys=Object.keys(dimNames) as Dim[];const points=keys.map((k,i)=>{const a=(-90+i*60)*Math.PI/180,r=dims[k]*.42;return`${50+Math.cos(a)*r}% ${50+Math.sin(a)*r}%`}).join(",");return <div className="radar"><div className="radar-grid g1"/><div className="radar-grid g2"/><div className="radar-grid g3"/><div className="radar-shape" style={{clipPath:`polygon(${points})`}}/>{keys.map((k,i)=>{const a=(-90+i*60)*Math.PI/180;return <span key={k} style={{left:`${50+Math.cos(a)*49}%`,top:`${50+Math.sin(a)*49}%`}}>{dimNames[k]}<b>{dims[k]}</b></span>})}</div>}

function Report({result,onReset,onShare,onHome}:{result:Result;onReset:()=>void;onShare:()=>void;onHome:()=>void}){const diff=result.mental-result.actual;const top=(Object.keys(result.dims) as Dim[]).sort((a,b)=>result.dims[b]-result.dims[a]);const low=top.slice(-2).reverse();const relation=result.dims.social>72?"成熟可靠的同行者":"温和主动的倾听者";const opposite=result.dims.curiosity>result.dims.responsibility?"稳定踏实的规划者":"天真鲜活的探索者";return <article className="report"><section className="result-hero"><header><b><i>M</i> INNER AGE</b><span>REPORT · {new Date().toLocaleDateString("zh-CN")}</span></header><span className="done-chip">测试完成</span><p>YOUR INNER PORTRAIT</p><h1>你的心理画像</h1><div className="age-compare"><div className="mental"><span>心理年龄</span><b>{result.mental}</b><em>岁</em></div><i>VS</i><div><span>实际年龄</span><b>{result.actual}</b><em>岁</em></div></div><h2>{Math.abs(diff)<=2?"你的身心年龄默契相融，知行合一。":diff>2?`你的内在比时间更沉稳 ${diff} 岁。`:`你保留着比时光年轻 ${Math.abs(diff)} 岁的生命力。`}</h2></section>
 <section className="identity-banner"><span>你的身份标签</span><h2>{result.title}</h2><p>{result.identity}</p>{result.keywords.map(k=><i key={k}>{k}</i>)}</section>
 <div className="report-body"><section className="report-section intro"><div className="section-title"><i>“</i><h2>性格深度解析</h2></div><p>你既能听见内心的需要，也愿意回应现实的要求。面对重要选择时，你不会只凭一时冲动，而会在经验、感受与长期价值之间寻找平衡。你最鲜明的力量来自<strong>{dimNames[top[0]]}</strong>和<strong>{dimNames[top[1]]}</strong>：这让你在变化里仍然能够保持自己的方向。</p><div className="tags">{result.keywords.map(k=><span key={k}>{k}</span>)}</div></section>
 <section className="report-section dimension"><div className="section-title"><i>⌁</i><h2>六维人格图谱</h2></div><p className="section-sub">分数表示你在本次情境选择中的相对倾向，不代表能力高低。</p><Radar dims={result.dims}/><div className="dim-list">{(Object.keys(dimNames) as Dim[]).map(d=><div key={d}><span>{dimNames[d]}<b>{result.dims[d]}</b></span><i><em style={{width:`${result.dims[d]}%`}}/></i></div>)}</div></section>
 <section className="report-section"><div className="section-title"><i>▥</i><h2>深度自我分析</h2></div><div className="insight-grid"><div className="strength"><span>CORE STRENGTHS</span><h3>核心优势</h3><ul><li>你在{dimNames[top[0]]}上表现突出，能把这种品质变成稳定的行动资源。</li><li>{dimNames[top[1]]}让你在复杂情境中，比多数人更容易找到合适的回应。</li><li>你愿意复盘自己的选择，而不是只追求一个漂亮答案。</li></ul></div><div className="blind"><span>GROWTH EDGES</span><h3>潜在盲点</h3><ul><li>当压力升高时，较弱的{dimNames[low[0]]}可能让你过度消耗自己。</li><li>优势使用过度也会成为负担：坚定可能变固执，敏感可能变内耗。</li><li>你不必在每件事上都证明成熟，适度求助同样是一种能力。</li></ul></div></div><div className="interpret"><h3>维度解读</h3><p>你的心理成熟不是“老成”，而是更能容纳矛盾。当前画像显示：你擅长用<strong>{dimNames[top[0]]}</strong>推进人生；下一阶段可把注意力放在<strong>{dimNames[low[0]]}</strong>上，让行动与感受更加均衡。</p></div></section>
 <section className="report-section"><div className="section-title pink"><i>♧</i><h2>社交与匹配</h2></div><div className="match-card main"><span>你的关系原型</span><h3>{relation}</h3><p>你看重真诚、稳定和彼此尊重，也希望重要关系经得起现实生活的考验。</p></div><div className="match-grid"><div><span>最佳拍档</span><h3>{result.dims.stability>70?"温柔坚定的建设者":"从容成熟的陪伴者"}</h3><p>彼此托底，也给对方足够空间。</p></div><div><span>互补搭档</span><h3>{opposite}</h3><p>对方能唤醒你较少使用的一面。</p></div></div></section>
 <section className="advice"><span>TO YOUR FUTURE SELF</span><h2>给未来的你</h2><p>继续认真生活，但别把自己逼得太紧。每周为纯粹的好奇留出一点时间；在重要决定前问自己：“这是我真正想要的，还是我觉得应该要的？”成熟不是永远正确，而是允许自己调整、休息和重新出发。</p><div className="score"><span>综合画像得分</span><b>{result.score}</b><em>/ 160</em></div></section>
 <section className="actions"><button onClick={onReset}>↻ 重新测试</button><button className="share" onClick={onShare}>⌁ 分享结果</button><button onClick={onHome}>返回首页</button><p>本测试用于自我探索与娱乐，不构成医学或心理诊断。</p></section></div></article>}
