const http=require("node:http"),crypto=require("node:crypto");
const PORT=9000,ENV=process.env.CLOUDBASE_ENV_ID||"inner-age-test-d9gb4g5uk995d5605",KEY=process.env.CLOUDBASE_API_KEY||"",ADMIN=process.env.ADMIN_SECRET||"",SECRET=process.env.SESSION_SECRET||"",DB=`https://${ENV}.api.tcloudbasegateway.com/v1/rdb/rest`;
const dimensions=["curiosity","responsibility","stability","social","acceptance","adaptability","responsibility","curiosity","stability","social","acceptance","adaptability","curiosity","responsibility","stability","social","adaptability","acceptance","responsibility","acceptance"],names={curiosity:"好奇心",stability:"情绪稳定",social:"社交开放",responsibility:"责任担当",adaptability:"适应力",acceptance:"自我接纳"};

function send(res,status,data,headers={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(status===204?"":JSON.stringify(data))}
function hash(v){return crypto.createHash("sha256").update(String(v)).digest("hex")}
function mac(v){return crypto.createHmac("sha256",SECRET).update(v).digest("base64url")}
function same(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function sign(payload){const value=Buffer.from(JSON.stringify(payload)).toString("base64url");return`${value}.${mac(value)}`}
function verify(token,scope){if(!token||!SECRET)return null;const[p,s]=token.split(".");if(!p||!s||!same(s,mac(p)))return null;try{const v=JSON.parse(Buffer.from(p,"base64url").toString());return v.scope===scope&&v.exp>Date.now()?v:null}catch{return null}}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||"").split(";").map(v=>v.trim().split("=")).filter(v=>v[0]).map(([k,...v])=>[k,decodeURIComponent(v.join("="))]))}
function cookie(name,value,seconds){return`${name}=${encodeURIComponent(value)}; Max-Age=${seconds}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function ip(req){return String(req.headers["x-forwarded-for"]||req.socket.remoteAddress||"unknown").split(",")[0].trim()}
async function input(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>65536)throw Object.assign(new Error("请求内容过大"),{status:413});chunks.push(c)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString()):{}}catch{throw Object.assign(new Error("请求格式错误"),{status:400})}}
async function db(table,{method="GET",query="",data,prefer}={}){if(!KEY)throw Object.assign(new Error("未配置 CLOUDBASE_API_KEY"),{status:503});const r=await fetch(`${DB}/${table}${query?`?${query}`:""}`,{method,headers:{Authorization:`Bearer ${KEY}`,"Content-Type":"application/json",Accept:"application/json",...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)}),text=await r.text();let value=null;try{value=text?JSON.parse(text):null}catch{value=text}if(!r.ok)throw Object.assign(new Error(value?.message||String(value||"数据库请求失败")),{status:r.status>=500?503:r.status});return value}
async function audit(action,detail,actor){try{await db("audit_logs",{method:"POST",data:{action,detail,actor_hash:hash(actor).slice(0,64)},prefer:"return=minimal"})}catch(e){console.error("audit",e.message)}}
async function limited(req,scope,max=10,window=900000){const id=hash(`${scope}:${ip(req)}`).slice(0,64),rows=await db("rate_limits",{query:`id=eq.${id}&select=*`}),now=Date.now(),old=rows?.[0];if(old?.blocked_until&&Date.parse(old.blocked_until)>now)throw Object.assign(new Error("尝试次数过多，请15分钟后再试"),{status:429});const fresh=!old||now-Date.parse(old.window_started_at)>=window,attempts=fresh?1:Number(old.attempts)+1,blocked=attempts>max?new Date(now+window).toISOString():null;await db("rate_limits",{method:"POST",query:"on_conflict=id",data:{id,scope,attempts,window_started_at:fresh?new Date(now).toISOString():old.window_started_at,blocked_until:blocked,updated_at:new Date(now).toISOString()},prefer:"resolution=merge-duplicates,return=minimal"});if(blocked)throw Object.assign(new Error("尝试次数过多，请15分钟后再试"),{status:429})}
function newCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",b=crypto.randomBytes(12),v=Array.from(b,x=>a[x%a.length]).join("");return`MIND-${v.slice(0,4)}-${v.slice(4,8)}-${v.slice(8)}`}
function device(req){let d=cookies(req).ia_device;return d||`${crypto.randomUUID()}${crypto.randomUUID()}`}

async function invite(req,res){await limited(req,"invite");const{code}=await input(req),normalized=String(code||"").trim().toUpperCase();if(!/^MIND-[A-Z2-9]{4}-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(normalized))return send(res,400,{valid:false,message:"邀请码格式不正确"});let rows=await db("invites",{query:`code=eq.${encodeURIComponent(normalized)}&select=*`}),record=rows?.[0];if(!record||record.disabled)return send(res,404,{valid:false,message:"邀请码不存在，请向购买渠道确认"});const now=Date.now();if(record.expires_at&&Date.parse(record.expires_at)<now)return send(res,410,{valid:false,message:"邀请码已超过24小时有效期"});const raw=device(req),dh=hash(raw);if(record.device_hash&&!same(record.device_hash,dh))return send(res,403,{valid:false,message:"该邀请码已绑定其他设备"});if(!record.device_hash){rows=await db("invites",{method:"PATCH",query:`code=eq.${encodeURIComponent(normalized)}&device_hash=is.null`,data:{activated_at:new Date(now).toISOString(),expires_at:new Date(now+86400000).toISOString(),device_hash:dh,usage_count:Number(record.usage_count)+1},prefer:"return=representation"});record=rows?.[0]||(await db("invites",{query:`code=eq.${encodeURIComponent(normalized)}&select=*`}))?.[0]}else await db("invites",{method:"PATCH",query:`code=eq.${encodeURIComponent(normalized)}&device_hash=eq.${dh}`,data:{usage_count:Number(record.usage_count)+1},prefer:"return=minimal"});if(!record||!same(record.device_hash,dh))return send(res,403,{valid:false,message:"该邀请码已绑定其他设备"});const exp=Date.parse(record.expires_at),seconds=Math.max(1,Math.floor((exp-now)/1000)),session=sign({scope:"test",code:normalized,deviceHash:dh,exp});return send(res,200,{valid:true,expiresAt:exp,remainingSeconds:seconds},{"Set-Cookie":[cookie("ia_device",raw,seconds),cookie("ia_session",session,seconds)]})}
function age(birth){const b=new Date(`${birth}T00:00:00`),n=new Date();if(Number.isNaN(b.getTime()))return-1;let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||n.getMonth()===b.getMonth()&&n.getDate()<b.getDate())a--;return a}
async function result(req,res){const c=cookies(req),session=verify(c.ia_session,"test");if(!session||!c.ia_device||hash(c.ia_device)!==session.deviceHash)return send(res,401,{message:"测试凭证已过期，请返回首页重新验证邀请码"});const{birth,answers}=await input(req),actual=age(String(birth||""));if(actual<10||actual>100||!Array.isArray(answers)||answers.length!==20||answers.some(v=>!Number.isInteger(v)||v<0||v>3))return send(res,400,{message:"答题数据不完整，请重新测试"});const sums={},counts={};Object.keys(names).forEach(k=>{sums[k]=0;counts[k]=0});dimensions.forEach((d,i)=>{sums[d]+=answers[i]+1;counts[d]++});const dims={};Object.keys(names).forEach(d=>dims[d]=Math.round(35+(sums[d]/counts[d]-1)*20));const avg=Object.values(dims).reduce((a,b)=>a+b,0)/6,mental=Math.max(16,Math.min(72,Math.round(actual+(avg-65)*.24+(dims.responsibility-dims.curiosity)*.07))),score=Math.round(Object.values(dims).reduce((a,b)=>a+b,0)*160/600);let title="从容成长的探索者",identity="清醒而温暖的同行者";if(dims.responsibility>78&&dims.stability>70){title="稳健进取的实干家";identity="有担当的长期主义者"}else if(dims.curiosity>78&&dims.adaptability>72){title="永远年轻的探索家";identity="带着热望的生活实验者"}else if(dims.social>78&&dims.acceptance>72){title="温暖通透的连接者";identity="细腻而坚定的共情者"}else if(avg<58){title="正在长出力量的青年";identity="敏感而真诚的成长者"}const sorted=Object.keys(dims).sort((a,b)=>dims[b]-dims[a]);send(res,200,{actual,mental,score,dims,title,identity,keywords:sorted.slice(0,4).map(d=>`#${names[d]}`)})}
async function adminSession(req,res){if(req.method==="GET")return send(res,200,{authenticated:!!verify(cookies(req).ia_admin,"admin")});if(req.method==="DELETE")return send(res,204,null,{"Set-Cookie":cookie("ia_admin","",0)});await limited(req,"admin",5);const{password}=await input(req);if(!ADMIN||!same(password||"",ADMIN)){await audit("admin_login_failed","invalid password",ip(req));return send(res,401,{message:"管理员密码错误"})}const exp=Date.now()+28800000;await audit("admin_login","success",ip(req));send(res,200,{ok:true},{"Set-Cookie":cookie("ia_admin",sign({scope:"admin",exp}),28800)})}
async function adminInvites(req,res){if(!verify(cookies(req).ia_admin,"admin"))return send(res,401,{message:"登录已过期，请重新登录"});if(req.method==="GET"){const [codes,logs]=await Promise.all([db("invites",{query:"select=*&order=created_at.desc&limit=1000"}),db("audit_logs",{query:"select=action,detail,created_at&order=created_at.desc&limit=30"})]);return send(res,200,{codes:(codes||[]).map(v=>({...v,created_at:Date.parse(v.created_at),activated_at:v.activated_at?Date.parse(v.activated_at):null,expires_at:v.expires_at?Date.parse(v.expires_at):null,device_bound:v.device_hash?1:0,device_hash:undefined})),logs:(logs||[]).map(v=>({...v,created_at:Date.parse(v.created_at)})),serverTime:Date.now()})}const{count}=await input(req),n=Math.max(1,Math.min(100,Number(count)||10)),records=Array.from({length:n},()=>({code:newCode()}));await db("invites",{method:"POST",data:records,prefer:"return=minimal"});await audit("invite_generate",`count=${n}`,ip(req));send(res,201,{created:records.map(v=>v.code)})}

async function route(req,res){const path=new URL(req.url,`http://${req.headers.host||"localhost"}`).pathname.replace(/\/+$/,"");if(req.method==="OPTIONS")return send(res,204,null);if(req.method==="GET"&&path.endsWith("/api/health")){try{await db("invites",{query:"select=code&limit=1"});return send(res,200,{status:"ok",database:"available",runtime:"cloudbase"})}catch(e){return send(res,503,{status:"degraded",database:"unavailable",message:e.message})}}if(req.method==="POST"&&path.endsWith("/api/invite"))return invite(req,res);if(req.method==="POST"&&path.endsWith("/api/result"))return result(req,res);if(path.endsWith("/api/admin/session")&&["GET","POST","DELETE"].includes(req.method))return adminSession(req,res);if(path.endsWith("/api/admin/invites")&&["GET","POST"].includes(req.method))return adminInvites(req,res);send(res,404,{message:"接口不存在"})}
http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);if(!res.headersSent)send(res,e.status||500,{message:e.status&&e.status<500?e.message:"服务暂时不可用"});else res.end()})).listen(PORT,"0.0.0.0",()=>console.log(`inner-age-api listening on ${PORT}`));
